TCM_CORE=tcm/
EXTRA_CFLAGS	+= -DCONFIG_TOUCHSCREEN_SYNA_TCM2_REFLASH
EXTRA_CFLAGS	+= -DCONFIG_TOUCHSCREEN_SYNA_TCM2_SYSFS
EXTRA_CFLAGS	+= -DCONFIG_TOUCHSCREEN_SYNA_TCM2_TESTING

obj-$(CONFIG_TOUCHSCREEN_SYNA_TCM2) = syna_touch.o
syna_touch-objs += \
			syna_tcm2.o \
			$(TCM_CORE)synaptics_touchcom_core_v1.o \
			$(TCM_CORE)synaptics_touchcom_core_v2.o \
			$(TCM_CORE)synaptics_touchcom_func_base.o \
			$(TCM_CORE)synaptics_touchcom_func_touch.o \
			$(TCM_CORE)synaptics_touchcom_func_reflash.o \
			$(TCM_CORE)synaptics_touchcom_func_romboot.o \
			syna_tcm2_platform_spi.o \
			syna_tcm2_sysfs.o \
			syna_tcm2_testing.o

KBUILD_EXTRA_SYMBOLS +=$(OUT)/obj/vendor/qcom/opensource/display-drivers/Module.symvers